import { Inter } from "next/font/google";
import "./globals.css";
// import "tailwindcss/tailwind.css";
// import "bootstrap/dist/css/bootstrap.min.css";
import StoreProvider from "./StoreProvider";
import ToastProvider from "@/components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToastProvider>{children}</ToastProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
